// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_nwB0rASK3fY08YDaeLn_h15sdywsjU',
    appId: '1:620006701548:web:abd2d0b4b1e9fa308628c9',
    messagingSenderId: '620006701548',
    projectId: 'flutter-gymapp-live-44ba2',
    authDomain: 'flutter-gymapp-live-44ba2.firebaseapp.com',
    storageBucket: 'flutter-gymapp-live-44ba2.appspot.com',
    measurementId: 'G-PD88PR4VF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBywTD4L9g0Ujta0jH5u8kksDp8yAzjzvU',
    appId: '1:620006701548:android:227a900f28fc7c608628c9',
    messagingSenderId: '620006701548',
    projectId: 'flutter-gymapp-live-44ba2',
    storageBucket: 'flutter-gymapp-live-44ba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMLVwUAECd6woAfQs64DX1n4hqviFQN4M',
    appId: '1:620006701548:ios:3e389a6ce0c1f38b8628c9',
    messagingSenderId: '620006701548',
    projectId: 'flutter-gymapp-live-44ba2',
    storageBucket: 'flutter-gymapp-live-44ba2.appspot.com',
    iosBundleId: 'mila.su.flutterGymappTeste',
  );
}
